export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://divyadarshan360.com"

export const seoKeywords = [
    "Divya Darshan 360",
    "Divya Darshan",
    "Durlabh Darshan",
    "TechXR",
    "Temple 360",
    "VR Darshan India",
    "VR temple darshan",
    "360 temple experience",
    "virtual reality temples",
    "Hindu temple VR",
    "spiritual VR experience",
    "temple aarti VR",
    "divine darshan",
    "virtual temple visit",
    "sacred places VR",
    "spiritual technology",
    "immersive temple experience",
    "360 degree temple tour",
    "virtual darshan",
    "online temple visit",
    "VR pilgrimage",
    "digital temple experience",
    "Hindu temples online",
    "spiritual VR app",
    "temple virtual tour",
    "sacred sites VR",
    "devotional VR",
    "temple 360 video",
    "virtual worship",
    "online aarti",
    "Online Aarti 360",
    "Virtual Puja",
    "Metaverse Temple",
    "Digital Sanctuary",
    "temple livestream",
    "Live Camera Feeds Temple",
    "E-Darshan",
    "Immersive Spiritual Journey",
    "Kashi Vishwanath VR",
    "Mahakal Temple VR",
    "Tirupati Virtual Darshan",
    "spiritual immersion",
    "VR religious experience",
    "Hindu devotional VR",
    "temple darshan online",
    "sacred VR journey",
    "immersive spirituality",
    "virtual pilgrimage experience",
    "temple exploration VR",
    "divine experience VR",
    "spiritual meditation VR",
    "Hindu culture VR",
    "temple architecture VR",
    "religious tourism VR",
    "sanctuary VR",
    "temple prayers VR",
    "spiritual enlightenment VR",
    "devotional technology",
    "sacred space VR",
];

export const defaultMetadata = {
    title: {
        default: "Divya Darshan 360 | Experience Divine VR Darshan",
        template: "%s | Divya Darshan 360",
    },
    description:
        "Immersive 360° virtual reality experiences of sacred Hindu temples, aartis, and spiritual wisdom. Experience divine darshan from anywhere in the world.",
}
